<a href="https://colab.research.google.com/github/sunyingjian/-Logging-related-network/blob/master/%E5%BB%B6%E5%AE%89%E6%B2%B9%E7%94%B0%E6%A0%87%E7%AD%BE%E4%BC%A0%E6%92%AD%E7%AE%97%E6%B3%95%E5%8D%8A%E7%9B%91%E7%9D%A3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### <font size=5px color="red">✦ *Google Colab 突破90分钟自动断开:</font>
<p><font size=3px > 每60分钟自动运行代码以刷新90分钟断开限制. 打开 developer-settings (在你的浏览器) 快速健 Ctrl+Shift+I 然后按console 输入以下代码 Enter. ( mac 按 Option+Command+I)</p><b>复制以下隐藏代码粉贴在浏览器console！！不要关闭浏览器以免失效</b>

<code>function ClickConnect(){
console.log("Working"); 
document.querySelector("colab-connect-button").click() 
}setInterval(ClickConnect,6000)</code>

In [ ]:
#@markdown <h3>← 输入了代码后运行以防止断开</h>


import IPython
from google.colab import output

display(IPython.display.Javascript('''
 function ClickConnect(){
   btn = document.querySelector("colab-connect-button")
   if (btn != null){
     console.log("Click colab-connect-button"); 
     btn.click() 
     }
   
   btn = document.getElementById('ok')
   if (btn != null){
     console.log("Click reconnect"); 
     btn.click() 
     }
  }
  
setInterval(ClickConnect,60000)
'''))

print("Done.")

<IPython.core.display.Javascript object>

Done.


#准备数据

In [ ]:
! git clone https://github.com/sunyingjian/numpy-.git
! git clone https://github.com/seg/tutorials-2016.git

Cloning into 'numpy-'...
remote: Enumerating objects: 89, done.
remote: Total 89 (delta 0), reused 0 (delta 0), pack-reused 89
Unpacking objects: 100% (89/89), done.
Cloning into 'tutorials-2016'...
remote: Enumerating objects: 161, done.
remote: Total 161 (delta 0), reused 0 (delta 0), pack-reused 161
Receiving objects: 100% (161/161), 16.86 MiB | 23.27 MiB/s, done.
Resolving deltas: 100% (64/64), done.


In [ ]:
import os
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [ ]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

In [ ]:
df_data_1 = pd.read_csv('/content/numpy-/半监督数据集/有标签数据集.csv')
df_data_2 = pd.read_csv('/content/numpy-/半监督数据集/无标签数据集.csv')
df_data_1

AC       CAL        GR  ...  Core Lithology  Unnamed: 7  Unnamed: 8
0    0.038756  0.026970  0.094776  ...               5         NaN         NaN
1    0.347382  0.090194  0.145150  ...               7         NaN         NaN
2    0.218400  0.059510  0.252165  ...               3         NaN         NaN
3    0.366064  0.082147  0.149304  ...               7         NaN         NaN
4    0.291877  0.079981  0.141782  ...               7         NaN         NaN
..        ...       ...       ...  ...             ...         ...         ...
361  0.016947  0.138827  0.118400  ...               6         NaN         NaN
362  0.131043  0.069016  0.029354  ...               3         NaN         NaN
363  0.036182  0.032010  0.030090  ...               5         NaN         NaN
364  0.014562  0.127332  0.035014  ...               6         NaN         NaN
365  0.014427  0.134185  0.033460  ...               6         NaN         NaN

[366 rows x 9 columns]

In [ ]:
df_data_2

AC       CAL        GR  ...        RD        SP  Core Lithology
0     0.029102  0.031789  0.026724  ...  0.078986  0.333754             NaN
1     0.032883  0.033469  0.030592  ...  0.076064  0.333669             NaN
2     0.034385  0.037006  0.032359  ...  0.074503  0.333619             NaN
3     0.243816  0.143381  0.086581  ...  0.017649  0.094025             NaN
4     0.248043  0.146786  0.084643  ...  0.017286  0.090554             NaN
...        ...       ...       ...  ...       ...       ...             ...
3340  0.012092  0.067866  0.007657  ...  0.181798  0.348797             NaN
3341  0.011831  0.069989  0.007606  ...  0.206839  0.348560             NaN
3342  0.011533  0.070121  0.009591  ...  0.250115  0.348470             NaN
3343  0.008903  0.069325  0.010596  ...  0.281774  0.348340             NaN
3344  0.003230  0.070210  0.012674  ...  0.329088  0.348228             NaN

[3345 rows x 7 columns]

In [ ]:
X_s= df_data_1.iloc[:,:6].values
y_s = df_data_1['Core Lithology'].values
X_t= df_data_2.iloc[:,:6].values
y_s

array([5, 7, 3, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 3, 7, 3, 3, 3, 7, 7, 3, 2,
       2, 7, 2, 3, 3, 7, 3, 7, 7, 7, 2, 7, 3, 2, 3, 2, 4, 3, 4, 3, 3, 7,
       7, 7, 7, 7, 7, 2, 7, 2, 3, 3, 3, 7, 2, 7, 3, 2, 7, 4, 2, 7, 3, 3,
       3, 3, 7, 4, 4, 3, 2, 7, 2, 4, 4, 3, 2, 7, 2, 2, 4, 3, 2, 2, 2, 2,
       3, 2, 4, 4, 2, 4, 2, 3, 7, 3, 2, 3, 7, 2, 3, 2, 3, 3, 7, 3, 3, 3,
       3, 3, 3, 3, 7, 2, 2, 2, 4, 2, 2, 2, 2, 2, 3, 7, 3, 2, 1, 2, 3, 3,
       2, 3, 3, 5, 3, 7, 3, 3, 7, 3, 3, 4, 5, 3, 7, 2, 7, 7, 3, 2, 3, 3,
       3, 3, 7, 7, 2, 7, 1, 1, 3, 1, 3, 3, 7, 1, 7, 3, 3, 3, 7, 3, 7, 7,
       3, 1, 3, 7, 7, 5, 1, 2, 3, 7, 2, 2, 3, 7, 4, 7, 7, 5, 7, 2, 7, 3,
       7, 3, 7, 3, 2, 7, 2, 7, 7, 1, 2, 2, 7, 7, 1, 7, 2, 3, 2, 3, 1, 7,
       7, 1, 2, 7, 1, 7, 2, 2, 7, 1, 5, 4, 5, 2, 2, 7, 2, 2, 5, 1, 3, 7,
       7, 5, 7, 2, 6, 2, 7, 1, 7, 2, 5, 7, 5, 2, 7, 7, 2, 7, 7, 7, 4, 2,
       7, 7, 7, 2, 4, 2, 7, 7, 6, 1, 7, 1, 2, 3, 3, 7, 4, 1, 4, 5, 2, 5,
       2, 2, 5, 5, 2, 5, 5, 6, 2, 2, 2, 3, 2, 5, 6,

In [ ]:
labels_s = np.copy(y_s)

#标签传播算法

In [ ]:
from sklearn.semi_supervised import LabelPropagation
laber_prop_model = LabelPropagation()
laber_prop_model.fit(X_s,y_s)

LabelPropagation(gamma=20, kernel='rbf', max_iter=1000, n_jobs=None,
                 n_neighbors=7, tol=0.001)

In [ ]:
#对没有标签的数据集使用LPA算法打上标签
Y_pred2 = laber_prop_model.predict(X_t)
print(Y_pred2)

[5 5 5 ... 5 5 5]


In [ ]:
X=np.append(X_s,X_t,axis=0)
X

array([[0.03875584, 0.02696967, 0.09477602, 0.11254278, 0.00141979,
        0.61450399],
       [0.34738218, 0.09019365, 0.14515003, 0.20233541, 0.00274352,
        0.33956822],
       [0.2184003 , 0.05951012, 0.25216485, 0.71129454, 0.00387403,
        0.91856718],
       ...,
       [0.01153279, 0.07012114, 0.00959134, 0.08133682, 0.25011533,
        0.34846983],
       [0.00890256, 0.06932532, 0.01059554, 0.08113549, 0.28177415,
        0.34834024],
       [0.00323044, 0.07020957, 0.01267433, 0.08012885, 0.32908795,
        0.34822757]])

In [ ]:
Y=np.append(y_s,Y_pred2,axis=0)
Y

array([5, 7, 3, ..., 5, 5, 5])

In [ ]:
Y_1=np.append(Y_pred2,y_s,axis=0)
true_data = pd.read_csv('/content/numpy-/延安油田总数居.csv')
Y_true = true_data['Core Lithology'].values

In [ ]:
from sklearn import metrics
print('标签传播Accuracy : %f' % (metrics.accuracy_score(Y_1, Y_true)))

标签传播Accuracy : 0.552412


#随机森林

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
        X, Y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics

rfmodel = RandomForestClassifier()
rfmodel.fit(X_train,y_train)
print('model')
print(rfmodel)

ypredrf1 = rfmodel.predict(X_test)
print('confusion matrix')
print(metrics.confusion_matrix(y_test, ypredrf1))
print('classification report')
print(metrics.classification_report(y_test, ypredrf1))
print('Accuracy : %f' % (metrics.accuracy_score(y_test, ypredrf1)))

model
RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)
confusion matrix
[[  3   0   4   0   0   0   0]
 [  0  75   8   0   0   0   7]
 [  0   4 265   1   2   0   5]
 [  0   1   1   0   0   0   2]
 [  0   0   7   0 115   0   0]
 [  0   0   0   0   0   3   1]
 [  1   2   8   0   0   0 228]]
classification report
              precision    recall  f1-score   support

           1       0.75      0.43      0.55         7
           2       0.91      0.83      0.87        90
           3       0.90    

#只使用有标签数据做随机森林

In [ ]:
from sklearn.model_selection import train_test_split
X_train_o, X_test_o, y_train_o, y_test_o = train_test_split(
        X_s, y_s, test_size=0.2, random_state=42)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics

rfmodel = RandomForestClassifier()
rfmodel.fit(X_train_o,y_train_o)
print('model')
print(rfmodel)

ypredrf1 = rfmodel.predict(X_test_o)
print('confusion matrix')
print(metrics.confusion_matrix(y_test_o, ypredrf1))
print('classification report')
print(metrics.classification_report(y_test_o, ypredrf1))
print('Accuracy : %f' % (metrics.accuracy_score(y_test_o, ypredrf1)))

model
RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)
confusion matrix
[[ 1  1  0  0  0  0  0]
 [ 0 14  1  0  0  0  1]
 [ 0  0 14  0  0  0  0]
 [ 0  3  0  3  0  0  0]
 [ 0  0  0  0 12  0  0]
 [ 0  0  0  0  0  1  0]
 [ 0  0  0  0  1  0 22]]
classification report
              precision    recall  f1-score   support

           1       1.00      0.50      0.67         2
           2       0.78      0.88      0.82        16
           3       0.93      1.00      0.97        14
           4       1.0